############################################################
# Dockerfile build ruby
# in ubuntu
############################################################

# Base image to ubuntu:16.04
FROM ubuntu:16.04

# Author
MAINTAINER Auli

# Run commands


