############################################################
# Dockerfile build mongodb container
# in ubuntu
############################################################

# Base image to ubuntu:16.04
FROM ubuntu-base:16.04

# Author
MAINTAINER Auli

# Run commands


